//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Shop_OrderForm
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string State { get; set; }
        public Nullable<int> WuliuId { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual T_Shop_Wuliu T_Shop_Wuliu { get; set; }
    }
}
